import type { Dish } from "./store";

// The real Highway Heaven menu (pure veg), extracted from the printed menu.
export const MENU_CATEGORIES = [
  "Soups",
  "Tandoori Starters",
  "Chaap",
  "Pakoda",
  "Momos",
  "Chinese",
  "Pizza",
  "Burgers",
  "Sandwiches",
  "Wraps",
  "Mexican Bites",
  "Pasta",
  "Pav Bhaji & Chilla",
  "Snacks & Sides",
  "Main Course",
  "Rice & Biryani",
  "Breads & Paratha",
  "Salads, Raita & Papad",
  "Beverages",
  "Mocktails",
  "Shakes",
  "Lassi & Chaas",
  "Ice Cream",
  "Sweets",
];

export const seedMenu: Dish[] = [
  { id: "m1", name: "Hot & Sour Soup", desc: "", price: 99, category: "Soups", veg: true, available: true },
  { id: "m2", name: "Manchow Soup", desc: "", price: 99, category: "Soups", veg: true, available: true },
  { id: "m3", name: "Sweet Corn Soup", desc: "", price: 99, category: "Soups", veg: true, available: true },
  { id: "m4", name: "Cream of Mushroom Soup", desc: "", price: 99, category: "Soups", veg: true, available: true },
  { id: "m5", name: "Paneer Tikka", desc: "", price: 259, category: "Tandoori Starters", veg: true, available: true, bestseller: true },
  { id: "m6", name: "Malai Paneer Tikka", desc: "", price: 269, category: "Tandoori Starters", veg: true, available: true },
  { id: "m7", name: "Achari Paneer Tikka", desc: "", price: 259, category: "Tandoori Starters", veg: true, available: true },
  { id: "m8", name: "Hariyali Paneer Tikka", desc: "", price: 269, category: "Tandoori Starters", veg: true, available: true },
  { id: "m9", name: "Mushroom Tikka", desc: "", price: 289, category: "Tandoori Starters", veg: true, available: true },
  { id: "m10", name: "Dahi Kabab", desc: "", price: 249, category: "Tandoori Starters", veg: true, available: true },
  { id: "m11", name: "Veg Seekh Kabab", desc: "", price: 279, category: "Tandoori Starters", veg: true, available: true },
  { id: "m12", name: "Hara Bhara Kabab", desc: "", price: 229, category: "Tandoori Starters", veg: true, available: true },
  { id: "m13", name: "Tandoori Platter", desc: "Paneer tikka, malai or masala chaap, mushroom tikka and seekh kabab.", price: 349, category: "Tandoori Starters", veg: true, available: true, bestseller: true },
  { id: "m14", name: "Masala Chaap (Starter)", desc: "", price: 279, category: "Chaap", veg: true, available: true },
  { id: "m15", name: "Malai Chaap (Starter)", desc: "", price: 289, category: "Chaap", veg: true, available: true },
  { id: "m16", name: "Achari Chaap (Starter)", desc: "", price: 249, category: "Chaap", veg: true, available: true },
  { id: "m17", name: "Hariyali Chaap (Starter)", desc: "", price: 249, category: "Chaap", veg: true, available: true },
  { id: "m18", name: "Kadai Chaap", desc: "", price: 289, category: "Chaap", veg: true, available: true },
  { id: "m19", name: "Handi Chaap", desc: "", price: 289, category: "Chaap", veg: true, available: true },
  { id: "m20", name: "Masala Chaap Gravy", desc: "", price: 279, category: "Chaap", veg: true, available: true },
  { id: "m21", name: "Chaap Butter Masala", desc: "", price: 299, category: "Chaap", veg: true, available: true },
  { id: "m22", name: "Chaap Korma", desc: "", price: 269, category: "Chaap", veg: true, available: true },
  { id: "m23", name: "Aloo Pakoda", desc: "8 pieces.", price: 109, category: "Pakoda", veg: true, available: true },
  { id: "m24", name: "Pyaaz Pakoda", desc: "8 pieces.", price: 119, category: "Pakoda", veg: true, available: true },
  { id: "m25", name: "Mix Pakoda", desc: "8 pieces.", price: 129, category: "Pakoda", veg: true, available: true },
  { id: "m26", name: "Paneer Pakoda", desc: "8 pieces.", price: 139, category: "Pakoda", veg: true, available: true },
  { id: "m27", name: "Veg Steam Momos", desc: "", price: 109, category: "Momos", veg: true, available: true },
  { id: "m28", name: "Veg Fried Momos", desc: "", price: 119, category: "Momos", veg: true, available: true },
  { id: "m29", name: "Paneer Steam Momos", desc: "", price: 129, category: "Momos", veg: true, available: true },
  { id: "m30", name: "Paneer Fried Momos", desc: "", price: 139, category: "Momos", veg: true, available: true },
  { id: "m31", name: "Cheese Corn Steam Momos", desc: "", price: 139, category: "Momos", veg: true, available: true },
  { id: "m32", name: "Cheese Corn Fried Momos", desc: "", price: 149, category: "Momos", veg: true, available: true },
  { id: "m33", name: "Veg Butter Fried Momos", desc: "", price: 139, category: "Momos", veg: true, available: true },
  { id: "m34", name: "Paneer Butter Fried Momos", desc: "", price: 159, category: "Momos", veg: true, available: true },
  { id: "m35", name: "Veg Gravy Momos", desc: "", price: 139, category: "Momos", veg: true, available: true },
  { id: "m36", name: "Paneer Gravy Momos", desc: "", price: 159, category: "Momos", veg: true, available: true },
  { id: "m37", name: "Veg Chilli Momos", desc: "", price: 139, category: "Momos", veg: true, available: true },
  { id: "m38", name: "Paneer Chilli Momos", desc: "", price: 159, category: "Momos", veg: true, available: true },
  { id: "m39", name: "Veg Kurkure Momos", desc: "", price: 149, category: "Momos", veg: true, available: true },
  { id: "m40", name: "Paneer Kurkure Momos", desc: "", price: 169, category: "Momos", veg: true, available: true },
  { id: "m41", name: "Veg Tandoori Momos", desc: "", price: 169, category: "Momos", veg: true, available: true, bestseller: true },
  { id: "m42", name: "Paneer Tandoori Momos", desc: "", price: 189, category: "Momos", veg: true, available: true },
  { id: "m43", name: "Veg Afghani Momos", desc: "", price: 189, category: "Momos", veg: true, available: true },
  { id: "m44", name: "Paneer Afghani Momos", desc: "", price: 199, category: "Momos", veg: true, available: true },
  { id: "m45", name: "Chilli Potato", desc: "", price: 159, category: "Chinese", veg: true, available: true },
  { id: "m46", name: "Honey Chilli Potato", desc: "", price: 169, category: "Chinese", veg: true, available: true },
  { id: "m47", name: "Chilli Paneer", desc: "", price: 199, category: "Chinese", veg: true, available: true, bestseller: true },
  { id: "m48", name: "Veg Hakka Noodles", desc: "", price: 179, category: "Chinese", veg: true, available: true },
  { id: "m49", name: "Schezwan Noodles", desc: "", price: 179, category: "Chinese", veg: true, available: true },
  { id: "m50", name: "Chilli Garlic Noodles", desc: "", price: 189, category: "Chinese", veg: true, available: true },
  { id: "m51", name: "Singapore Noodles", desc: "", price: 189, category: "Chinese", veg: true, available: true },
  { id: "m52", name: "Paneer Noodles", desc: "", price: 189, category: "Chinese", veg: true, available: true },
  { id: "m53", name: "Crispy Corn Noodles", desc: "", price: 189, category: "Chinese", veg: true, available: true },
  { id: "m54", name: "Veg Fried Rice", desc: "", price: 159, category: "Chinese", veg: true, available: true },
  { id: "m55", name: "Paneer Fried Rice", desc: "", price: 179, category: "Chinese", veg: true, available: true },
  { id: "m56", name: "Chilli Garlic Fried Rice", desc: "", price: 179, category: "Chinese", veg: true, available: true },
  { id: "m57", name: "Veg Manchurian", desc: "", price: 159, category: "Chinese", veg: true, available: true },
  { id: "m58", name: "Paneer Manchurian", desc: "", price: 179, category: "Chinese", veg: true, available: true },
  { id: "m59", name: "Chinese Sizzler", desc: "Fries, manchurian, hakka noodles and chilli potato on one plate.", price: 299, category: "Chinese", veg: true, available: true, bestseller: true },
  { id: "m60", name: "Margherita Pizza", desc: "Add-on: extra cheese or paneer ₹50 — mention it in your order note.", price: 199, category: "Pizza", veg: true, available: true },
  { id: "m61", name: "Cheese Corn Pizza", desc: "", price: 229, category: "Pizza", veg: true, available: true },
  { id: "m62", name: "Onion Tomato & Capsicum Pizza", desc: "", price: 249, category: "Pizza", veg: true, available: true },
  { id: "m63", name: "Peppy Paneer Pizza", desc: "", price: 259, category: "Pizza", veg: true, available: true },
  { id: "m64", name: "Farmhouse Pizza", desc: "", price: 289, category: "Pizza", veg: true, available: true },
  { id: "m65", name: "Mexican Delight Pizza", desc: "", price: 289, category: "Pizza", veg: true, available: true },
  { id: "m66", name: "Cheese Burst Pizza", desc: "", price: 319, category: "Pizza", veg: true, available: true },
  { id: "m67", name: "Mac & Cheese Pizza", desc: "", price: 319, category: "Pizza", veg: true, available: true },
  { id: "m68", name: "Tandoori Paneer Pizza", desc: "", price: 329, category: "Pizza", veg: true, available: true, bestseller: true },
  { id: "m69", name: "Classic Veg Burger", desc: "", price: 59, category: "Burgers", veg: true, available: true },
  { id: "m70", name: "Spicy Peri Peri Burger", desc: "", price: 79, category: "Burgers", veg: true, available: true },
  { id: "m71", name: "Veg Cheesy Burger", desc: "", price: 79, category: "Burgers", veg: true, available: true },
  { id: "m72", name: "Crispy Paneer Burger", desc: "", price: 99, category: "Burgers", veg: true, available: true },
  { id: "m73", name: "Cheese Burst Burger", desc: "", price: 99, category: "Burgers", veg: true, available: true },
  { id: "m74", name: "Veg Grilled Sandwich", desc: "", price: 99, category: "Sandwiches", veg: true, available: true },
  { id: "m75", name: "Cheese Corn Sandwich", desc: "", price: 119, category: "Sandwiches", veg: true, available: true },
  { id: "m76", name: "Peppy Paneer Sandwich", desc: "", price: 119, category: "Sandwiches", veg: true, available: true },
  { id: "m77", name: "Paneer Tikka Sandwich", desc: "", price: 129, category: "Sandwiches", veg: true, available: true },
  { id: "m78", name: "Club Sandwich", desc: "", price: 139, category: "Sandwiches", veg: true, available: true },
  { id: "m79", name: "Cheese Paneer Veg Sandwich", desc: "", price: 149, category: "Sandwiches", veg: true, available: true },
  { id: "m80", name: "Cheese Veg Wrap", desc: "", price: 99, category: "Wraps", veg: true, available: true },
  { id: "m81", name: "Schezwan Wrap", desc: "", price: 129, category: "Wraps", veg: true, available: true },
  { id: "m82", name: "Paneer Cheese Wrap", desc: "", price: 129, category: "Wraps", veg: true, available: true },
  { id: "m83", name: "Tandoori Paneer Wrap", desc: "", price: 139, category: "Wraps", veg: true, available: true },
  { id: "m84", name: "Exotic Quesadilla", desc: "", price: 119, category: "Mexican Bites", veg: true, available: true },
  { id: "m85", name: "Tandoori Paneer Quesadilla", desc: "", price: 129, category: "Mexican Bites", veg: true, available: true },
  { id: "m86", name: "Nachos with Salsa", desc: "", price: 109, category: "Mexican Bites", veg: true, available: true },
  { id: "m87", name: "Red Sauce Pasta", desc: "", price: 189, category: "Pasta", veg: true, available: true },
  { id: "m88", name: "White Sauce Pasta", desc: "", price: 199, category: "Pasta", veg: true, available: true },
  { id: "m89", name: "Mix Sauce Pasta", desc: "", price: 209, category: "Pasta", veg: true, available: true },
  { id: "m90", name: "Mac & Cheese Pasta", desc: "", price: 219, category: "Pasta", veg: true, available: true },
  { id: "m91", name: "Masala Pav Bhaji", desc: "", price: 109, category: "Pav Bhaji & Chilla", veg: true, available: true },
  { id: "m92", name: "Paneer Pav Bhaji", desc: "", price: 139, category: "Pav Bhaji & Chilla", veg: true, available: true },
  { id: "m93", name: "Cheese Pav Bhaji", desc: "", price: 139, category: "Pav Bhaji & Chilla", veg: true, available: true },
  { id: "m94", name: "Peri-Peri Besan Chilla", desc: "", price: 109, category: "Pav Bhaji & Chilla", veg: true, available: true },
  { id: "m95", name: "Cheese Garlic Bread", desc: "", price: 139, category: "Snacks & Sides", veg: true, available: true },
  { id: "m96", name: "Olive Cheese Garlic Bread", desc: "", price: 159, category: "Snacks & Sides", veg: true, available: true },
  { id: "m97", name: "Veggie Garlic Bread", desc: "", price: 179, category: "Snacks & Sides", veg: true, available: true },
  { id: "m98", name: "Jalapeño Garlic Bread", desc: "", price: 179, category: "Snacks & Sides", veg: true, available: true },
  { id: "m99", name: "Exotic Garlic Bread", desc: "", price: 179, category: "Snacks & Sides", veg: true, available: true },
  { id: "m100", name: "Salted Fries", desc: "", price: 79, category: "Snacks & Sides", veg: true, available: true },
  { id: "m101", name: "Peri-Peri Fries", desc: "", price: 89, category: "Snacks & Sides", veg: true, available: true },
  { id: "m102", name: "Fries with Cheese Dip", desc: "", price: 99, category: "Snacks & Sides", veg: true, available: true },
  { id: "m103", name: "Onion Rings", desc: "", price: 129, category: "Snacks & Sides", veg: true, available: true },
  { id: "m104", name: "Potato Wedges", desc: "", price: 89, category: "Snacks & Sides", veg: true, available: true },
  { id: "m105", name: "Kadai Paneer", desc: "", price: 289, category: "Main Course", veg: true, available: true },
  { id: "m106", name: "Shahi Paneer", desc: "", price: 289, category: "Main Course", veg: true, available: true },
  { id: "m107", name: "Matar Paneer", desc: "", price: 249, category: "Main Course", veg: true, available: true },
  { id: "m108", name: "Paneer Do Pyaaza", desc: "", price: 289, category: "Main Course", veg: true, available: true },
  { id: "m109", name: "Paneer Lababdar", desc: "", price: 289, category: "Main Course", veg: true, available: true },
  { id: "m110", name: "Handi Paneer", desc: "", price: 319, category: "Main Course", veg: true, available: true },
  { id: "m111", name: "Paneer Butter Masala", desc: "", price: 289, category: "Main Course", veg: true, available: true, bestseller: true },
  { id: "m112", name: "Paneer Korma", desc: "", price: 299, category: "Main Course", veg: true, available: true },
  { id: "m113", name: "Paneer Bhurji", desc: "", price: 289, category: "Main Course", veg: true, available: true },
  { id: "m114", name: "Paneer Tikka Masala", desc: "", price: 319, category: "Main Course", veg: true, available: true },
  { id: "m115", name: "Paneer Angara", desc: "", price: 349, category: "Main Course", veg: true, available: true },
  { id: "m116", name: "Veg Kofta", desc: "", price: 249, category: "Main Course", veg: true, available: true },
  { id: "m117", name: "Malai Kofta", desc: "", price: 289, category: "Main Course", veg: true, available: true },
  { id: "m118", name: "Malai Kofta White Gravy", desc: "", price: 319, category: "Main Course", veg: true, available: true },
  { id: "m119", name: "Mix Veg", desc: "", price: 229, category: "Main Course", veg: true, available: true },
  { id: "m120", name: "Navratan Korma", desc: "A Highway Heaven special.", price: 329, category: "Main Course", veg: true, available: true, bestseller: true },
  { id: "m121", name: "Kashmiri Dum Aloo", desc: "", price: 199, category: "Main Course", veg: true, available: true },
  { id: "m122", name: "Banarasi Dum Aloo", desc: "", price: 219, category: "Main Course", veg: true, available: true },
  { id: "m123", name: "Stuffed Tomato", desc: "", price: 219, category: "Main Course", veg: true, available: true },
  { id: "m124", name: "Dal Fry", desc: "", price: 159, category: "Main Course", veg: true, available: true },
  { id: "m125", name: "Dal Tadka", desc: "", price: 189, category: "Main Course", veg: true, available: true },
  { id: "m126", name: "Dal Makhani", desc: "", price: 229, category: "Main Course", veg: true, available: true },
  { id: "m127", name: "Masala Jeera Aloo", desc: "", price: 149, category: "Main Course", veg: true, available: true },
  { id: "m128", name: "Methi Aloo", desc: "", price: 149, category: "Main Course", veg: true, available: true },
  { id: "m129", name: "Matar Mushroom", desc: "", price: 249, category: "Main Course", veg: true, available: true },
  { id: "m130", name: "Mushroom Butter Masala", desc: "", price: 289, category: "Main Course", veg: true, available: true },
  { id: "m131", name: "Handi Mushroom", desc: "", price: 319, category: "Main Course", veg: true, available: true },
  { id: "m132", name: "Tawa Mushroom", desc: "", price: 289, category: "Main Course", veg: true, available: true },
  { id: "m133", name: "Kadai Mushroom", desc: "", price: 289, category: "Main Course", veg: true, available: true },
  { id: "m134", name: "Mushroom Do Pyaaza", desc: "", price: 289, category: "Main Course", veg: true, available: true },
  { id: "m135", name: "Mushroom Lababdar", desc: "", price: 289, category: "Main Course", veg: true, available: true },
  { id: "m136", name: "Plain Rice", desc: "", price: 109, category: "Rice & Biryani", veg: true, available: true },
  { id: "m137", name: "Jeera Rice", desc: "", price: 129, category: "Rice & Biryani", veg: true, available: true },
  { id: "m138", name: "Veg Pulao", desc: "", price: 149, category: "Rice & Biryani", veg: true, available: true },
  { id: "m139", name: "Veg Biryani", desc: "", price: 229, category: "Rice & Biryani", veg: true, available: true },
  { id: "m140", name: "Paneer Biryani", desc: "", price: 249, category: "Rice & Biryani", veg: true, available: true },
  { id: "m141", name: "Mushroom Biryani", desc: "", price: 249, category: "Rice & Biryani", veg: true, available: true },
  { id: "m142", name: "Hyderabadi Biryani", desc: "", price: 289, category: "Rice & Biryani", veg: true, available: true },
  { id: "m143", name: "Plain Tawa Roti", desc: "", price: 15, category: "Breads & Paratha", veg: true, available: true },
  { id: "m144", name: "Butter Tawa Roti", desc: "", price: 20, category: "Breads & Paratha", veg: true, available: true },
  { id: "m145", name: "Plain Tandoori Roti", desc: "", price: 20, category: "Breads & Paratha", veg: true, available: true },
  { id: "m146", name: "Butter Tandoori Roti", desc: "", price: 25, category: "Breads & Paratha", veg: true, available: true },
  { id: "m147", name: "Missi Roti", desc: "", price: 35, category: "Breads & Paratha", veg: true, available: true },
  { id: "m148", name: "Plain Naan", desc: "", price: 40, category: "Breads & Paratha", veg: true, available: true },
  { id: "m149", name: "Butter Naan", desc: "", price: 50, category: "Breads & Paratha", veg: true, available: true },
  { id: "m150", name: "Stuffed Naan", desc: "", price: 70, category: "Breads & Paratha", veg: true, available: true },
  { id: "m151", name: "Paneer Stuffed Naan", desc: "", price: 80, category: "Breads & Paratha", veg: true, available: true },
  { id: "m152", name: "Laccha Paratha", desc: "", price: 45, category: "Breads & Paratha", veg: true, available: true },
  { id: "m153", name: "Pudina Paratha", desc: "", price: 50, category: "Breads & Paratha", veg: true, available: true },
  { id: "m154", name: "Mirchi Paratha", desc: "", price: 45, category: "Breads & Paratha", veg: true, available: true },
  { id: "m155", name: "Aloo Paratha", desc: "", price: 89, category: "Breads & Paratha", veg: true, available: true },
  { id: "m156", name: "Pyaaz Paratha", desc: "", price: 109, category: "Breads & Paratha", veg: true, available: true },
  { id: "m157", name: "Mix Paratha", desc: "", price: 119, category: "Breads & Paratha", veg: true, available: true },
  { id: "m158", name: "Paneer Paratha", desc: "", price: 129, category: "Breads & Paratha", veg: true, available: true },
  { id: "m159", name: "Green Salad", desc: "", price: 59, category: "Salads, Raita & Papad", veg: true, available: true },
  { id: "m160", name: "Onion Salad", desc: "", price: 49, category: "Salads, Raita & Papad", veg: true, available: true },
  { id: "m161", name: "Mix Salad", desc: "", price: 69, category: "Salads, Raita & Papad", veg: true, available: true },
  { id: "m162", name: "Plain Curd", desc: "", price: 59, category: "Salads, Raita & Papad", veg: true, available: true },
  { id: "m163", name: "Jeera Curd", desc: "", price: 69, category: "Salads, Raita & Papad", veg: true, available: true },
  { id: "m164", name: "Boondi Raita", desc: "", price: 99, category: "Salads, Raita & Papad", veg: true, available: true },
  { id: "m165", name: "Veg Raita", desc: "", price: 99, category: "Salads, Raita & Papad", veg: true, available: true },
  { id: "m166", name: "Onion Raita", desc: "", price: 99, category: "Salads, Raita & Papad", veg: true, available: true },
  { id: "m167", name: "Pineapple Raita", desc: "", price: 129, category: "Salads, Raita & Papad", veg: true, available: true },
  { id: "m168", name: "Dry Papad", desc: "", price: 20, category: "Salads, Raita & Papad", veg: true, available: true },
  { id: "m169", name: "Fry Papad", desc: "", price: 25, category: "Salads, Raita & Papad", veg: true, available: true },
  { id: "m170", name: "Masala Papad", desc: "", price: 59, category: "Salads, Raita & Papad", veg: true, available: true },
  { id: "m171", name: "Tea", desc: "Ginger, masala or elaichi.", price: 39, category: "Beverages", veg: true, available: true },
  { id: "m172", name: "Black Coffee", desc: "", price: 49, category: "Beverages", veg: true, available: true },
  { id: "m173", name: "Plain Hot Coffee", desc: "", price: 59, category: "Beverages", veg: true, available: true },
  { id: "m174", name: "Chocolate Hot Coffee", desc: "", price: 69, category: "Beverages", veg: true, available: true },
  { id: "m175", name: "Plain Cold Coffee", desc: "", price: 109, category: "Beverages", veg: true, available: true },
  { id: "m176", name: "Cold Coffee with Ice Cream", desc: "", price: 129, category: "Beverages", veg: true, available: true, bestseller: true },
  { id: "m177", name: "Cold Coffee with Chocolate", desc: "", price: 129, category: "Beverages", veg: true, available: true },
  { id: "m178", name: "Cold Drink 350ml", desc: "Fanta, Sprite, Coke etc.", price: 35, category: "Beverages", veg: true, available: true },
  { id: "m179", name: "Soft Drink Can", desc: "Charged at MRP.", price: 40, category: "Beverages", veg: true, available: true },
  { id: "m180", name: "Virgin Mojito", desc: "", price: 129, category: "Mocktails", veg: true, available: true },
  { id: "m181", name: "Green Apple Mojito", desc: "", price: 129, category: "Mocktails", veg: true, available: true },
  { id: "m182", name: "Fruit Punch Mojito", desc: "", price: 129, category: "Mocktails", veg: true, available: true },
  { id: "m183", name: "Blue Lagoon", desc: "", price: 129, category: "Mocktails", veg: true, available: true },
  { id: "m184", name: "Watermelon Mojito", desc: "", price: 129, category: "Mocktails", veg: true, available: true },
  { id: "m185", name: "Ginger & Lemon Mojito", desc: "", price: 129, category: "Mocktails", veg: true, available: true },
  { id: "m186", name: "Fresh Lime Soda", desc: "", price: 79, category: "Mocktails", veg: true, available: true },
  { id: "m187", name: "Masala Lemonade", desc: "", price: 129, category: "Mocktails", veg: true, available: true },
  { id: "m188", name: "Vanilla Shake", desc: "", price: 129, category: "Shakes", veg: true, available: true },
  { id: "m189", name: "Strawberry Shake", desc: "", price: 129, category: "Shakes", veg: true, available: true },
  { id: "m190", name: "Chocolate Shake", desc: "", price: 129, category: "Shakes", veg: true, available: true },
  { id: "m191", name: "Butterscotch Shake", desc: "", price: 129, category: "Shakes", veg: true, available: true },
  { id: "m192", name: "Pineapple Shake", desc: "", price: 129, category: "Shakes", veg: true, available: true },
  { id: "m193", name: "Mango Shake", desc: "", price: 129, category: "Shakes", veg: true, available: true },
  { id: "m194", name: "Oreo Shake", desc: "", price: 129, category: "Shakes", veg: true, available: true, bestseller: true },
  { id: "m195", name: "Kit-Kat Shake", desc: "", price: 129, category: "Shakes", veg: true, available: true },
  { id: "m196", name: "Plain Lassi", desc: "", price: 79, category: "Lassi & Chaas", veg: true, available: true },
  { id: "m197", name: "Lassi with Dry Fruits", desc: "", price: 99, category: "Lassi & Chaas", veg: true, available: true },
  { id: "m198", name: "Masala Chaas", desc: "", price: 69, category: "Lassi & Chaas", veg: true, available: true },
  { id: "m199", name: "Vanilla Ice Cream", desc: "", price: 69, category: "Ice Cream", veg: true, available: true },
  { id: "m200", name: "Strawberry Ice Cream", desc: "", price: 69, category: "Ice Cream", veg: true, available: true },
  { id: "m201", name: "Chocolate Ice Cream", desc: "", price: 79, category: "Ice Cream", veg: true, available: true },
  { id: "m202", name: "Butterscotch Ice Cream", desc: "", price: 79, category: "Ice Cream", veg: true, available: true },
  { id: "m203", name: "Gulab Jamun (2 pcs)", desc: "", price: 49, category: "Sweets", veg: true, available: true },
  { id: "m204", name: "White Rasgulla (2 pcs)", desc: "", price: 49, category: "Sweets", veg: true, available: true },
];
